[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_404 = "9kfP7Pvonn3sV7vLWVyEFbtH9LxuXN9B7UENQAZ4T39w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/brooke/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
